# Import Numpy

In [1]:
import numpy as np

In [2]:
# not possible on lists
[1,2,3,4] + 5

TypeError: can only concatenate list (not "int") to list

In [4]:
# Possible with arrays
np.array([1,2,3,4]) + 5

array([6, 7, 8, 9])

In [6]:
np.array([1,2,3,4]) * 5

array([ 5, 10, 15, 20])

In [7]:
x = np.array([1,2,3,4], dtype = float)

In [8]:
x

array([1., 2., 3., 4.])

# Multi-dimensional arrays

In [9]:
y = np.array([[1,2,3], [4,5,6]])

In [10]:
# Check shape - 2 rows, 3 columns
y.shape

(2, 3)

# Converting lists to arrays

In [11]:
alist = [4,5,67]

In [12]:
np.array(alist)

array([ 4,  5, 67])

# Lists of Ones and Zeros

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
# 3 rows and 3 columns
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 4 rows and 3 columns
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# arange

In [18]:
# list range (0,4)
list(range(0,4))

[0, 1, 2, 3]

In [19]:
np.arange(0,4)

array([0, 1, 2, 3])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# Linspace

In [22]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Random Arrays

In [33]:
# one random integer
np.random.randint(100)

93

In [41]:
# 100 random numbers from normal distribution
np.random.randn(100)

array([ 0.8138945 ,  1.23650089, -0.09395308, -1.21652799, -1.64186811,
        1.78984161,  0.29815804, -0.60731675,  0.37248587, -0.48538757,
        0.88619874, -1.99205194,  1.03780792,  1.63473734,  0.2804224 ,
        0.98995343, -0.16277432,  1.70555892, -0.01924379, -0.2067191 ,
       -0.07705042,  0.67666739,  1.26063446,  0.02087024, -0.19441529,
       -0.77223614, -1.64244188,  0.25043578,  0.09291493,  0.30711371,
       -1.71241315, -0.72350468,  1.69150645,  0.25161597,  0.08574334,
       -1.71913387, -1.27285848, -0.92880609,  0.08602875,  0.70058477,
       -0.70867846,  0.56717379, -0.54862789, -0.68817648,  0.66760418,
       -0.41392045,  0.53996894,  1.44689406,  1.28479458, -0.89409389,
       -1.17677338, -0.48585159,  0.78969667, -0.11464767,  2.47571962,
       -0.3561481 ,  0.18809308,  1.04453603, -1.07534715,  0.37873977,
       -0.01983224,  2.27781011,  1.37235998,  0.51692845, -1.11164329,
       -1.29069189, -0.27755423, -0.34732773, -0.03632914, -0.41

In [45]:
# from random numbers
np.random.rand(5)

array([0.49187112, 0.03024013, 0.61070134, 0.49823837, 0.39085096])

# Reshaping arrays

In [46]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# 1 row, 6 columns
y.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [48]:
y.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
y.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Multi-dimensional Slicing

In [51]:
z = np.array([[1,2,3,4], [10,11,12,13], [15,16,17,18]])

In [52]:
z

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [53]:
z[0]

array([1, 2, 3, 4])

In [54]:
z[1][3]

13

In [55]:
z[0][2]

3

In [57]:
z[:1, :2]

array([[1, 2]])

# List Operations

In [58]:
z

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [59]:
z.mean()

10.166666666666666

In [60]:
z.min()

1

In [61]:
z.max()

18

In [62]:
z.std()

5.899623340142619

In [63]:
z.sum()

122

# Change Data type

In [64]:
z

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [65]:
z.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [10., 11., 12., 13.],
       [15., 16., 17., 18.]])